# Generated by Django 5.2.7 on 2026-03-10 00:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_alter_clinic_address_alter_clinic_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'inventory_categories',
                'ordering': ['name'],
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('SUPPLY', 'Supply')], default='PRODUCT', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACK', 'Pack'), ('VIAL', 'Vial'), ('TUBE', 'Tube'), ('ML', 'mL'), ('MG', 'mg'), ('G', 'g'), ('OTHER', 'Other')], default='PCS', max_length=20)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Alert when stock falls to or below this level.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_products', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='e.g. invoice number, PO number', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['clinic', 'is_archived'], name='inventory_p_clinic__ff1f37_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_3b9fee_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_type'], name='inventory_p_item_ty_792130_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_5d59fa_idx'),
        ),
    ]
