# Generated by Django 5.2.7 on 2026-03-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_clinic'),
        ('clinics', '0004_alter_clinic_address_alter_clinic_city_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='clinic_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summary_notifications', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_BOOKING', 'New Appointment Booking'), ('DAILY_SUMMARY', 'Daily Appointments Summary')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx'),
        ),
    ]
