# Generated by Django 5.2.7 on 2026-03-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_clinic'),
        ('clinics', '0004_alter_clinic_address_alter_clinic_city_and_more'),
        ('notifications', '0003_clinic_wide_notifications'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_5cf777_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationread',
            new_name='notificatio_user_id_ddbde1_idx',
            old_name='notif_read_user_notif_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['clinic', 'created_at'], name='notificatio_clinic__10f8ad_idx'),
        ),
    ]
