# Generated by Django 5.2.7 on 2026-04-11 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_confirmation_sent_and_more'),
        ('clinics', '0013_cliniccommunicationsettings'),
        ('notifications', '0004_remove_notification_notificatio_user_id_5cf777_idx_and_more'),
        ('patients', '0008_patient_last_checkin_sent_at_patient_last_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comm_type', models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('RECURRING_CONFIRMATION', 'Recurring Booking Confirmation'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('DNA_FOLLOWUP', 'DNA / Decline Follow-up'), ('REBOOK_FOLLOWUP', 'No-Rebook Follow-up'), ('INACTIVE_CHECKIN', 'Inactive Patient Check-in'), ('CANCELLATION_NOTICE', 'Cancellation Notice')], db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=5)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered'), ('REPLIED', 'Replied')], default='SENT', max_length=10)),
                ('recipient', models.CharField(help_text='Email or phone number', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_preview', models.TextField(blank=True, help_text='First 500 chars of message body')),
                ('error_message', models.TextField(blank=True)),
                ('patient_reply', models.CharField(blank=True, help_text='Y or N', max_length=10)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='clinics.clinic')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='patients.patient')),
            ],
            options={
                'db_table': 'communication_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'comm_type', 'created_at'], name='communicati_clinic__e38ecb_idx'), models.Index(fields=['patient', 'comm_type'], name='communicati_patient_3fb293_idx'), models.Index(fields=['appointment', 'comm_type'], name='communicati_appoint_57dce7_idx')],
            },
        ),
    ]
