# Generated by Django 5.2.7 on 2026-08-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_patient_case'),
        ('notifications', '0008_notification_patient_notification_practitioner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='direction',
            field=models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound'), ('SYSTEM', 'System')], default='OUTBOUND', max_length=10),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='event_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores unstructured event transition data (e.g., old_date vs new_date)'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='related_appointment',
            field=models.ForeignKey(blank=True, help_text='Used to link original vs rescheduled appointments if necessary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_communication_logs', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('SYSTEM', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='comm_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('RECURRING_CONFIRMATION', 'Recurring Booking Confirmation'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('DNA_FOLLOWUP', 'DNA / Decline Follow-up'), ('REBOOK_FOLLOWUP', 'No-Rebook Follow-up'), ('INACTIVE_CHECKIN', 'Inactive Patient Check-in'), ('CANCELLATION_NOTICE', 'Cancellation Notice'), ('CLINICAL_NOTE', 'Clinical Note Email'), ('OTP_VERIFICATION', 'OTP Verification'), ('PASSWORD_RESET', 'Password Reset'), ('INVOICE_EMAIL', 'Invoice Email'), ('RESCHEDULE_FOLLOWUP', 'Reschedule Follow-up'), ('SYSTEM_NOTIFICATION', 'System Notification'), ('RESCHEDULE_REQUEST', 'Reschedule Request'), ('RESCHEDULE_CONFIRMATION', 'Reschedule Confirmation'), ('CANCELLATION', 'Cancellation Event'), ('PATIENT_RESPONSE', 'Patient Response'), ('DNA_EVENT', 'DNA Event')], db_index=True, max_length=30),
        ),
    ]
