# Generated by Django 5.2.7 on 2026-09-05 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_communicationlog_direction_and_more'),
        ('support', '0002_userfeedback_resolution_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='If set, this notification is meant ONLY for this user. If null, it is clinic-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='support.userfeedback'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_BOOKING', 'New Appointment Booking'), ('NEW_CLIENT', 'New Client'), ('ONLINE_BOOKING', 'New Online Booking'), ('DAILY_SUMMARY', 'Daily Appointments Summary'), ('FEEDBACK_RESOLVED', 'Feedback Resolved')], db_index=True, max_length=30),
        ),
    ]
