# Generated by Django 5.2.7 on 2026-09-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_recipient_notification_related_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_feedback',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_feedback_id',
            field=models.IntegerField(blank=True, help_text='Links to support.UserFeedback without enforcing cross-app FK constraints.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='If set, this notification is ONLY visible to this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
