# Generated by Django 5.2.7 on 2026-02-21 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_make_practitioner_optional'),
        ('clinics', '0002_clinic_branch_code_clinic_is_main_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(help_text='Specific clinic branch for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic'),
        ),
    ]
