# Generated by Django 5.2.7 on 2026-03-17 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_clinic'),
        ('clinic_services', '0001_initial'),
        ('clinics', '0006_alter_clinic_city_alter_clinic_province'),
        ('patients', '0005_patient_archived_at_patient_archived_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Clinic service this appointment is for (replaces hardcoded type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic_services.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('INITIAL', 'Initial Consultation'), ('FOLLOW_UP', 'Follow-up'), ('THERAPY', 'Therapy Session'), ('ASSESSMENT', 'Assessment')], default='INITIAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['service', 'date'], name='appointment_service_a0ae8a_idx'),
        ),
    ]
