# Generated by Django 5.2.7 on 2026-03-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrival_status',
            field=models.CharField(blank=True, choices=[('NO_STATUS', 'No Status'), ('ARRIVED', 'Arrived'), ('DNA', 'Did Not Arrive')], default='NO_STATUS', help_text='Tracks whether the practitioner has arrived for the appointment', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('ARRIVED', 'Arrived'), ('DNA', 'Did Not Arrive')], default='SCHEDULED', max_length=20),
        ),
    ]
