# Generated by Django 5.2.7 on 2026-03-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_arrival_status_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrival_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the practitioner marked arrival', null=True),
        ),
    ]
