# Generated by Django 5.2.7 on 2026-03-27 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_arrival_time'),
        ('clinics', '0006_alter_clinic_city_alter_clinic_province'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_name', models.CharField(help_text='Name/title of the blocked event (e.g., Staff Meeting)', max_length=200)),
                ('event_type', models.CharField(choices=[('BLOCK', 'Blocked Schedule')], default='BLOCK', editable=False, max_length=20)),
                ('date', models.DateField(help_text='Date of the blocked event')),
                ('start_time', models.TimeField(help_text='Start time of the blocked period')),
                ('end_time', models.TimeField(help_text='End time of the blocked period')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the blocked event')),
                ('clinic', models.ForeignKey(help_text='Clinic/branch this block event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='block_appointments', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_appointments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'block_appointments',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['clinic', 'date'], name='block_appoi_clinic__3e35e8_idx'), models.Index(fields=['date'], name='block_appoi_date_aec6f3_idx')],
            },
        ),
    ]
