# Generated by Django 5.2.7 on 2026-04-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_blockappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dna_followup_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dna_followup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_reply',
            field=models.CharField(blank=True, help_text='Y or N reply from patient via SMS.', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rebook_followup_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rebook_followup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurring_group_id',
            field=models.CharField(blank=True, help_text='Shared ID linking appointments in the same recurring series.', max_length=50),
        ),
    ]
