# Generated by Django 5.2.7 on 2026-04-18 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_confirmation_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockappointment',
            name='visibility_type',
            field=models.CharField(choices=[('ALL', 'All Users'), ('SELECTED', 'Selected Users')], default='ALL', help_text='Controls who can see this block appointment', max_length=10),
        ),
        migrations.AddField(
            model_name='blockappointment',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can see this block (only applies when visibility_type=SELECTED)', related_name='visible_block_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
