# Generated by Django 5.2.7 on 2026-04-18 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_blockappointment_visibility_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockappointment',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this block appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_appointments_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockappointment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this block appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_appointments_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
