# Generated by Django 5.2.7 on 2026-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_blockappointment_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockappointment',
            name='visibility_type',
            field=models.CharField(choices=[('ALL', 'All Users'), ('SELECTED', 'Selected Users'), ('SELF', 'Myself Only')], default='ALL', help_text='Controls who can see this block appointment', max_length=15),
        ),
    ]
