# Generated by Django 5.2.7 on 2026-01-23 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('philhealth_accreditation', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_plan', models.CharField(choices=[('TRIAL', 'Trial'), ('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='TRIAL', max_length=20)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='clinics.clinic')),
            ],
            options={
                'db_table': 'clinic_locations',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('license_number', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('prc_license', models.CharField(blank=True, max_length=100, verbose_name='PRC License')),
                ('philhealth_accreditation', models.CharField(blank=True, max_length=100)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bio', models.TextField(blank=True)),
                ('is_accepting_patients', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to='clinics.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practitioners',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
