# Generated by Django 5.2.7 on 2026-02-21 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='branch_code',
            field=models.CharField(blank=True, help_text='Unique branch identifier', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_main_branch',
            field=models.BooleanField(default=True, help_text='Is this the main clinic?'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='parent_clinic',
            field=models.ForeignKey(blank=True, help_text='Parent clinic if this is a branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='clinics.clinic'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['parent_clinic', 'is_active'], name='clinics_parent__9a4ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['branch_code'], name='clinics_branch__bc0b7a_idx'),
        ),
    ]
