# Generated by Django 5.2.7 on 2026-02-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_branch_code_clinic_is_main_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='branch_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique branch identifier', max_length=100, null=True, unique=True),
        ),
    ]
