# Generated by Django 5.2.7 on 2026-03-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_clinic_address_alter_clinic_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='setup_complete',
            field=models.BooleanField(default=False, help_text='True once the admin has completed the initial clinic profile setup.'),
        ),
    ]
