# Generated by Django 5.2.7 on 2026-03-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinic_setup_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='province',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
