# Generated by Django 5.2.7 on 2026-04-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_alter_clinic_city_alter_clinic_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='duty_days',
            field=models.JSONField(default=list, help_text='List of duty days, e.g. ["Mon", "Tue", "Wed"]'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='duty_end_time',
            field=models.TimeField(default='17:00', help_text='Duty end time'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='duty_start_time',
            field=models.TimeField(default='08:00', help_text='Duty start time'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='lunch_end_time',
            field=models.TimeField(default='13:00', help_text='Lunch break end time'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='lunch_start_time',
            field=models.TimeField(default='12:00', help_text='Lunch break start time'),
        ),
    ]
