# Generated by Django 5.2.7 on 2026-04-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_practitioner_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='discipline',
            field=models.CharField(choices=[('OCCUPATIONAL_THERAPY', 'Occupational Therapy'), ('SPEECH_LANGUAGE_PATHOLOGIST', 'Speech Language Pathologist'), ('PHYSICAL_THERAPY', 'Physical Therapy'), ('OSTEOPATHY', 'Osteopathy'), ('DENTISTRY', 'Dentistry'), ('MD_GENERAL_PRACTITIONER', 'MD: General Practitioner')], default='OCCUPATIONAL_THERAPY', max_length=50),
        ),
    ]
