# Generated by Django 5.2.7 on 2026-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_practitioner_duty_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='duty_end_time',
            field=models.TimeField(default='17:00', help_text='Duty end time (legacy – superseded by duty_schedule)'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='duty_start_time',
            field=models.TimeField(default='08:00', help_text='Duty start time (legacy – superseded by duty_schedule)'),
        ),
    ]
