# Generated by Django 5.2.7 on 2026-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_alter_practitioner_duty_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='custom_location',
            field=models.CharField(blank=True, help_text='Manual free-text location when standard search fails', max_length=500),
        ),
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
