# Generated by Django 5.2.7 on 2026-04-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_add_location_coords_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master switch: when False, NO automated or manual emails are sent.'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for SMS notifications (placeholder — not yet active).'),
        ),
    ]
