# Generated by Django 5.2.7 on 2026-04-11 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_add_notification_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_confirmation_method', models.CharField(choices=[('EMAIL', 'Email Only'), ('SMS', 'SMS Only'), ('BOTH', 'Email & SMS')], default='EMAIL', help_text='How to send booking confirmations.', max_length=5)),
                ('reminder_method', models.CharField(choices=[('EMAIL', 'Email Only'), ('SMS', 'SMS Only'), ('BOTH', 'Email & SMS')], default='EMAIL', help_text='How to send appointment reminders.', max_length=5)),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Send reminder this many hours before the appointment.')),
                ('no_rebook_followup_days', models.PositiveIntegerField(default=30, help_text='Days to wait after DNA/decline before sending rebook follow-up.')),
                ('inactive_patient_months', models.PositiveIntegerField(default=3, help_text='Months of inactivity before sending wellness check-in.')),
                ('booking_confirmations_enabled', models.BooleanField(default=True, help_text='Send booking confirmation upon appointment creation.')),
                ('reminders_enabled', models.BooleanField(default=True, help_text='Send appointment reminders.')),
                ('dna_followup_enabled', models.BooleanField(default=True, help_text='Send follow-up after DNA / patient declines.')),
                ('rebook_followup_enabled', models.BooleanField(default=True, help_text="Send delayed rebook follow-up if patient hasn't rescheduled.")),
                ('inactive_checkin_enabled', models.BooleanField(default=True, help_text='Send wellness check-in to inactive patients.')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_settings', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'Clinic communication settings',
                'db_table': 'clinic_communication_settings',
            },
        ),
    ]
