# Generated by Django 5.2.7 on 2026-03-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PRACTITIONER', 'Practitioner'), ('CLINIC', 'Clinic'), ('LABORATORY', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('SUPPLIER', 'Supplier'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
