# Generated by Django 5.2.7 on 2026-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_services', '0003_add_discipline_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_package',
            field=models.BooleanField(default=False, help_text='If true, this service functions as a treatment package'),
        ),
        migrations.AddField(
            model_name='service',
            name='session_allocation',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sessions approved when this package is booked. Required if is_package is True.', null=True),
        ),
    ]
