# Generated by Django 5.2.7 on 2026-03-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clinics', '0004_alter_clinic_address_alter_clinic_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to clinic logo image', max_length=500)),
                ('clinic_name', models.CharField(blank=True, help_text='Override clinic name on invoice', max_length=200)),
                ('clinic_address', models.TextField(blank=True, help_text='Full address to display')),
                ('clinic_phone', models.CharField(blank=True, max_length=50)),
                ('clinic_email', models.EmailField(blank=True, max_length=254)),
                ('clinic_website', models.URLField(blank=True)),
                ('tin_number', models.CharField(blank=True, help_text='Tax Identification Number', max_length=50)),
                ('header_text', models.TextField(blank=True, help_text='Text shown at top of invoice')),
                ('footer_text', models.TextField(blank=True, default='Thank you for your business!', help_text='Text shown at bottom of invoice')),
                ('terms_conditions', models.TextField(blank=True, help_text='Default terms & conditions')),
                ('payment_instructions', models.TextField(blank=True, help_text='Payment instructions shown on invoice')),
                ('primary_color', models.CharField(default='#0284c7', help_text='Hex color for headers/accents', max_length=7)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_clinic_info', models.BooleanField(default=True)),
                ('show_patient_info', models.BooleanField(default=True)),
                ('show_appointment_info', models.BooleanField(default=True)),
                ('show_payment_info', models.BooleanField(default=True)),
                ('currency_symbol', models.CharField(default='₱', max_length=10)),
                ('date_format', models.CharField(default='%B %d, %Y', help_text='Python strftime format', max_length=30)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_print_settings', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Invoice Print Settings',
                'verbose_name_plural': 'Invoice Print Settings',
                'db_table': 'invoice_print_settings',
            },
        ),
    ]
