# Generated by Django 5.2.7 on 2026-03-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceprintsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='clinic_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='date_format',
            field=models.CharField(default='%B %d, %Y', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='footer_text',
            field=models.TextField(blank=True, default='Thank you for your business!'),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='header_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='primary_color',
            field=models.CharField(default='#0284c7', max_length=7),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
