# Generated by Django 5.2.7 on 2026-04-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('BDO', 'BDO Unibank'), ('METROBANK', 'Metropolitan Bank & Trust Company'), ('BPI', 'Bank of the Philippine Islands'), ('LANDBANK', 'Land Bank of the Philippines'), ('PNB', 'Philippine National Bank'), ('SECURITY', 'Security Bank'), ('CHINABANK', 'China Banking Corporation'), ('UNIONBANK', 'Union Bank of the Philippines'), ('RCBC', 'Rizal Commercial Banking Corporation'), ('EASTWEST', 'East West Banking Corporation'), ('DBP', 'Development Bank of the Philippines'), ('AUB', 'Asia United Bank')], default='', max_length=20),
        ),
    ]
