# Generated by Django 5.2.7 on 2026-08-03 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_ageingdebtentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_billing_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='version_number',
            field=models.PositiveIntegerField(default=1, help_text='Current version number; increments with each edit.'),
        ),
        migrations.CreateModel(
            name='InvoiceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Invoice Created'), ('UPDATED', 'Invoice Updated (new version)'), ('VIEWED', 'Invoice Viewed'), ('PRINTED', 'Invoice Printed'), ('EMAILED', 'Invoice Emailed'), ('DELETED', 'Invoice Deleted'), ('PAYMENT', 'Payment Added')], max_length=20)),
                ('version', models.PositiveIntegerField(blank=True, help_text='Version number this action relates to.', null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Field-level changes for UPDATED actions.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='billing.invoice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'action', 'created_at'], name='invoice_aud_invoice_361785_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('philhealth_coverage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hmo_coverage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_notes', models.TextField(blank=True)),
                ('items_snapshot', models.JSONField(default=list, help_text='Snapshot of all line items at this version.')),
                ('change_summary', models.JSONField(blank=True, default=dict, help_text='Dict of changed fields: {field: {from: old, to: new}}')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoice_versions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='billing.invoice')),
            ],
            options={
                'db_table': 'invoice_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['invoice', 'version_number'], name='invoice_ver_invoice_40126a_idx')],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'version_number'), name='unique_invoice_version')],
            },
        ),
    ]
