# Generated by Django 5.2.7 on 2026-08-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_patient_case'),
        ('billing', '0006_add_invoice_versioning_and_audit'),
        ('patients', '0038_patientcase_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='patient_case',
            field=models.ForeignKey(blank=True, help_text='If set, this Invoice serves as the Master Invoice for the Case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoices', to='patients.patientcase'),
        ),
        migrations.AddField(
            model_name='invoiceversion',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='The appointment that generated this invoice version.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='invoiceversion',
            name='payment_made',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The payment contributed during this specific version/session.', max_digits=10),
        ),
    ]
