# Generated by Django 5.2.7 on 2026-03-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_services', '0001_initial'),
        ('patients', '0002_rename_service_to_portal_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalbooking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_bookings', to='clinic_services.service'),
        ),
    ]
