# Generated by Django 5.2.7 on 2026-03-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_clinic'),
        ('patients', '0003_alter_portalbooking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalbooking',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_booking', to='appointments.appointment'),
        ),
    ]
