# Generated by Django 5.2.7 on 2026-03-08 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_clinic_address_alter_clinic_city_and_more'),
        ('patients', '0004_portalbooking_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the patient was archived.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who archived this patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived patients are hidden from the active client list and diary.'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'is_archived'], name='patient_clinic_archived_idx'),
        ),
    ]
