# Generated by Django 5.2.7 on 2026-03-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_archived_at_patient_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allow_push_notifications',
            field=models.BooleanField(default=False, help_text='Allow push notifications for updates and reminders.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='data_sharing_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Patient preferences for data sharing with third parties.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='send_email_notifications',
            field=models.BooleanField(default=True, help_text='Send email notifications automatically for appointment reminders.'),
        ),
    ]
