# Generated by Django 5.2.7 on 2026-04-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send SMS notifications for appointment reminders (when SMS is enabled).'),
        ),
    ]
