# Generated by Django 5.2.7 on 2026-04-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_add_sms_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_checkin_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time an inactive-patient wellness check-in was sent.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_visit_date',
            field=models.DateField(blank=True, help_text="Date of the patient's most recent completed appointment.", null=True),
        ),
    ]
