# Generated by Django 5.2.7 on 2026-07-27 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_patient_case'),
        ('billing', '0005_ageingdebtentry'),
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('patients', '0030_patientcasesessionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_source', models.CharField(choices=[('MANUAL', 'Manual'), ('PACKAGE', 'Prepaid Package'), ('HMO', 'HMO Approval')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('UNLIMITED', 'Unlimited')], default='ACTIVE', max_length=20)),
                ('approved_sessions', models.IntegerField(blank=True, help_text='Total approved. Null if unlimited.', null=True)),
                ('used_sessions', models.IntegerField(default=0, help_text='Total used sessions based on invoices.')),
                ('is_unlimited', models.BooleanField(default=False, help_text='True if the allocation has no session limit.')),
                ('patient_case', models.OneToOneField(help_text='The case this allocation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='session_allocation', to='patients.patientcase')),
            ],
            options={
                'db_table': 'session_allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('USED', 'Used'), ('ADDED', 'Added'), ('REMOVED', 'Removed'), ('RESET', 'Reset'), ('UNLIMITED_SET', 'Set to Unlimited')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for manual adjustments or consumption notes')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_logs', to='patients.sessionallocation')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='billing.invoice')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='clinics.practitioner')),
            ],
            options={
                'db_table': 'session_consumption_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['allocation', 'action'], name='session_con_allocat_398f51_idx')],
            },
        ),
    ]
