# Generated by Django 5.2.7 on 2026-07-28 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_sessionallocation_sessionconsumptionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_merged',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates this duplicate patient was merged into a primary patient.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the patient was merged.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed the merge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='The primary patient this duplicate was merged into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='PatientMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merge_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for merging these profiles.')),
                ('relationships_transferred', models.JSONField(blank=True, default=dict, help_text='Detailed JSON map of all related IDs transferred. e.g. {"appointments": [1, 2], "cases": [5]}')),
                ('duplicate_patient', models.ForeignKey(help_text='The patient that was archived/merged.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='merges_as_duplicate', to='patients.patient')),
                ('merged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_merges_performed', to=settings.AUTH_USER_MODEL)),
                ('primary_patient', models.ForeignKey(help_text='The patient that survived the merge.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='merges_as_primary', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_merge_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
