# Generated by Django 5.2.7 on 2026-07-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_patient_is_merged_patient_merged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalbooking',
            name='patient_address_barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalbooking',
            name='patient_address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalbooking',
            name='patient_address_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalbooking',
            name='patient_address_street',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalbooking',
            name='patient_emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portalbooking',
            name='patient_emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
