# Generated by Django 5.2.7 on 2026-07-30 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_patient_case'),
        ('billing', '0005_ageingdebtentry'),
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('patients', '0033_patient_barangay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionallocation',
            name='patient_case',
        ),
        migrations.RemoveField(
            model_name='sessionconsumptionlog',
            name='allocation',
        ),
        migrations.RemoveIndex(
            model_name='sessionconsumptionlog',
            name='session_con_allocat_398f51_idx',
        ),
        migrations.AddField(
            model_name='patientcase',
            name='completed_sessions',
            field=models.IntegerField(default=0, help_text='Total used sessions based on invoices.'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='True if the allocation has no session limit.'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='session_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PACKAGE', 'Prepaid Package'), ('HMO', 'HMO Approval')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionconsumptionlog',
            name='patient_case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_logs', to='patients.patientcase'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='sessionconsumptionlog',
            index=models.Index(fields=['patient_case', 'action'], name='session_con_patient_8e120f_idx'),
        ),
        migrations.DeleteModel(
            name='SessionAllocation',
        ),
    ]
