# Generated by Django 5.2.7 on 2026-07-30 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_ageingdebtentry'),
        ('patients', '0034_remove_sessionallocation_patient_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid for this package.', max_digits=10),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='package_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost of the package.', max_digits=10),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='package_invoice',
            field=models.ForeignKey(blank=True, help_text='The designated Package Invoice for financial tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_cases', to='billing.invoice'),
        ),
    ]
