# Generated by Django 5.2.7 on 2026-08-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_patientcase_amount_paid_patientcase_package_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsentdocument',
            name='patient_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_documents', to='patients.patientcase'),
        ),
    ]
