# Generated by Django 5.2.7 on 2026-08-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_patient_case'),
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('patients', '0036_patientconsentdocument_patient_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientconsentdocument',
            options={'ordering': ['-signed_at'], 'verbose_name': 'Patient Consent Document', 'verbose_name_plural': 'Patient Consent Documents'},
        ),
        migrations.AddConstraint(
            model_name='patientconsentdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('patient_case__isnull', False)), fields=('patient_case', 'type'), name='unique_consent_per_case_type'),
        ),
    ]
