# Generated by Django 5.2.7 on 2026-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0037_alter_patientconsentdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True if the case is soft-deleted.'),
        ),
    ]
