# Generated by Django 5.2.7 on 2026-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0038_patientcase_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='account_notes',
            field=models.TextField(blank=True, default='', help_text="Internal notes regarding the patient's overall account and billing status."),
        ),
    ]
