# Generated by Django 5.2.7 on 2026-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_patient_account_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Active'), ('DISCHARGED', 'Discharged')], default='OPEN', max_length=20),
        ),
    ]
