# Generated by Django 5.2.7 on 2026-03-01 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', 'create_missing_practitioner_profiles'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinics', '0003_alter_clinic_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic_branch',
            field=models.ForeignKey(blank=True, help_text='Specific branch this staff/practitioner is assigned to. Null means they work across all branches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_users', to='clinics.clinic'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['clinic_branch'], name='users_clinic__59b7bf_idx'),
        ),
    ]
