# Generated by Django 5.2.7 on 2026-04-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_clinic_branch_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
