# Generated by Django 5.2.7 on 2026-01-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note_type', models.CharField(choices=[('SOAP', 'SOAP Note'), ('PROGRESS', 'Progress Note'), ('INITIAL', 'Initial Evaluation'), ('DISCHARGE', 'Discharge Summary')], default='SOAP', max_length=20)),
                ('date', models.DateField()),
                ('subjective', models.TextField(blank=True, help_text='Patient reported symptoms')),
                ('objective', models.TextField(blank=True, help_text='Clinical observations')),
                ('assessment', models.TextField(blank=True, help_text='Clinical assessment/diagnosis')),
                ('plan', models.TextField(blank=True, help_text='Treatment plan')),
                ('vital_signs', models.JSONField(blank=True, default=dict)),
                ('diagnosis_codes', models.JSONField(blank=True, default=list, help_text='ICD-10 codes')),
                ('treatment_codes', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True, help_text='Full note content (HTML)')),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_note', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='clinics.practitioner')),
            ],
            options={
                'db_table': 'clinical_notes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('XRAY', 'X-Ray'), ('LAB', 'Lab Result'), ('OTHER', 'Other')], max_length=20)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.clinicalnote')),
            ],
            options={
                'db_table': 'clinical_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('note_type', models.CharField(choices=[('SOAP', 'SOAP Note'), ('PROGRESS', 'Progress Note'), ('INITIAL', 'Initial Evaluation'), ('DISCHARGE', 'Discharge Summary')], max_length=20)),
                ('subjective_template', models.TextField(blank=True)),
                ('objective_template', models.TextField(blank=True)),
                ('assessment_template', models.TextField(blank=True)),
                ('plan_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_templates', to='clinics.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measure_name', models.CharField(help_text='e.g., Pain Scale, ROM, etc.', max_length=200)),
                ('date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_measures', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_measures', to='clinics.practitioner')),
            ],
            options={
                'db_table': 'outcome_measures',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['patient', 'date'], name='clinical_no_patient_9b5825_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['practitioner', 'date'], name='clinical_no_practit_5c6a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['clinic', 'date'], name='clinical_no_clinic__da2190_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomemeasure',
            index=models.Index(fields=['patient', 'measure_name', 'date'], name='outcome_mea_patient_9b0981_idx'),
        ),
    ]
