# Generated by Django 5.2.7 on 2026-01-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMOClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(max_length=100, unique=True)),
                ('claim_date', models.DateField()),
                ('service_date', models.DateField()),
                ('hmo_provider', models.CharField(max_length=200)),
                ('hmo_number', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmo_claims', to='clinics.clinic')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hmo_claims', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmo_claims', to='patients.patient')),
            ],
            options={
                'db_table': 'hmo_claims',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='PhilHealthClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(max_length=100, unique=True)),
                ('claim_date', models.DateField()),
                ('service_date', models.DateField()),
                ('philhealth_number', models.CharField(max_length=50)),
                ('case_type', models.CharField(max_length=100)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='philhealth_claims', to='clinics.clinic')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='philhealth_claims', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='philhealth_claims', to='patients.patient')),
            ],
            options={
                'db_table': 'philhealth_claims',
                'ordering': ['-claim_date'],
            },
        ),
    ]
