# Generated by Django 5.2.7 on 2026-08-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='category',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
    ]
