# Generated by Django 5.2.7 on 2026-08-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('letters', '0002_alter_lettertemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='clinic_branch',
            field=models.ForeignKey(blank=True, help_text='Specific branch this template is for. Null means all locations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_letter_templates', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='discipline',
            field=models.CharField(blank=True, default='', help_text='Practitioner discipline this template is designed for', max_length=100),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='layout_addressee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='layout_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='layout_letter_head',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='layout_remove_top_space',
            field=models.BooleanField(default=False),
        ),
    ]
