# Generated by Django 5.2.7 on 2026-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_lettertemplate_clinic_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='layout_addressee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='layout_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='layout_letter_head',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='layout_remove_top_space',
            field=models.BooleanField(default=False),
        ),
    ]
