# Generated by Django 5.2.7 on 2026-01-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('APPOINTMENTS', 'Appointments Report'), ('REVENUE', 'Revenue Report'), ('PATIENT', 'Patient Statistics'), ('PRACTITIONER', 'Practitioner Performance'), ('CLINICAL', 'Clinical Outcomes')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_format', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('EXCEL', 'Excel')], max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clinics.clinic')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'report_type', 'created_at'], name='reports_clinic__174e7f_idx')],
            },
        ),
    ]
