# Generated by Django 5.2.7 on 2026-03-08 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_clinic_address_alter_clinic_city_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tab',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'Administration'), ('CLINIC', 'Clinic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('UNINVOICED_BOOKINGS', 'Uninvoiced Bookings'), ('CANCELLATIONS', 'Cancellations'), ('CLIENTS_CASES', 'Clients & Cases'), ('CLINICAL_NOTES', 'Clinical Notes'), ('APPOINTMENTS', 'Appointments Report'), ('REVENUE', 'Revenue Report'), ('PATIENT', 'Patient Statistics'), ('PRACTITIONER', 'Practitioner Performance'), ('CLINICAL', 'Clinical Outcomes')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['clinic', 'tab', 'created_at'], name='reports_clinic__0a087c_idx'),
        ),
    ]
