# Generated by Django 5.2.7 on 2026-02-27 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_alter_appointment_clinic'),
        ('clinics', '0002_clinic_branch_code_clinic_is_main_branch_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('INITIAL', 'Initial Assessment'), ('FOLLOW_UP', 'Follow-up Note'), ('PROGRESS', 'Progress Note'), ('DISCHARGE', 'Discharge Summary'), ('SOAP', 'SOAP Note'), ('CUSTOM', 'Custom Template')], max_length=20)),
                ('structure', models.JSONField(default=dict, help_text='JSON schema defining form fields and sections')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(help_text='Template is scoped to this clinic', on_delete=django.db.models.deletion.CASCADE, related_name='clinical_templates', to='clinics.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_templates_v2', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, help_text='Reference to original template if this is a new version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='clinical_templates.clinicaltemplate')),
            ],
            options={
                'db_table': 'clinical_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('template_version', models.PositiveIntegerField(blank=True, help_text='Snapshot of template version at creation', null=True)),
                ('encrypted_content', models.TextField(blank=True, default='', help_text='AES encrypted JSON content')),
                ('date', models.DateField()),
                ('note_type', models.CharField(default='CLINICAL', max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('last_autosave', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_note_v2', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes_v2', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes_v2', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes_v2', to='clinics.practitioner')),
                ('template', models.ForeignKey(blank=True, help_text='Reference to template used (for audit only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='clinical_templates.clinicaltemplate')),
            ],
            options={
                'db_table': 'clinical_notes_v2',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNoteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATED', 'Note Created'), ('UPDATED', 'Note Updated'), ('SIGNED', 'Note Signed'), ('VIEWED', 'Note Viewed'), ('DELETED', 'Note Deleted')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Snapshot of changes made (encrypted fields logged as "ENCRYPTED")')),
                ('clinical_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='clinical_templates.clinicalnote')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_note_audits_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_note_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinical_note', 'action', 'created_at'], name='clinical_no_clinica_c1d39d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clinicaltemplate',
            index=models.Index(fields=['clinic', 'is_active', 'is_archived'], name='clinical_te_clinic__481c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaltemplate',
            index=models.Index(fields=['category'], name='clinical_te_categor_8786f8_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaltemplate',
            index=models.Index(fields=['parent_template', 'version'], name='clinical_te_parent__dac56a_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicaltemplate',
            constraint=models.UniqueConstraint(fields=('clinic', 'name', 'version'), name='unique_template_version_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['patient', 'date'], name='clinical_no_patient_ec7311_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['practitioner', 'date'], name='clinical_no_practit_0e5bab_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['clinic', 'date'], name='clinical_no_clinic__480c73_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['is_draft', 'is_signed'], name='clinical_no_is_draf_534a05_idx'),
        ),
    ]
