# Generated by Django 5.2.7 on 2026-03-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnoteauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Note Created'), ('UPDATED', 'Note Updated'), ('SIGNED', 'Note Signed'), ('VIEWED', 'Note Viewed'), ('DELETED', 'Note Deleted'), ('EMAILED', 'Note Emailed')], max_length=20),
        ),
    ]
