# Generated by Django 5.2.7 on 2026-03-27 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_arrival_time'),
        ('clinical_templates', '0002_alter_clinicalnoteauditlog_action'),
        ('clinics', '0006_alter_clinic_city_alter_clinic_province'),
        ('patients', '0005_patient_archived_at_patient_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes_v2', to='appointments.appointment'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['appointment'], name='clinical_no_appoint_257b06_idx'),
        ),
    ]
