# Generated by Django 5.2.7 on 2026-03-27 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_arrival_time'),
        ('clinical_templates', '0003_alter_clinicalnote_appointment_and_more'),
        ('clinics', '0006_alter_clinic_city_alter_clinic_province'),
        ('patients', '0005_patient_archived_at_patient_archived_by_and_more'),
    ]

    operations = [
        # Make appointment a required field with CASCADE delete (deletes note if appointment deleted)
        migrations.AlterField(
            model_name='clinicalnote',
            name='appointment',
            field=models.ForeignKey(
                blank=False,
                null=False,  # Required - appointment must be specified
                on_delete=django.db.models.deletion.CASCADE,  # Delete notes when appointment is deleted
                related_name='clinical_notes_v2',
                to='appointments.appointment'
            ),
        ),
    ]