# Generated by Django 5.2.7 on 2026-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_templates', '0004_alter_clinicalnote_appointment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltemplate',
            name='discipline',
            field=models.CharField(blank=True, default='', help_text='Practitioner discipline this template is designed for', max_length=100),
        ),
    ]
