# Generated by Django 5.2.7 on 2026-04-09 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_templates', '0005_add_discipline_field'),
        ('clinics', '0010_alter_practitioner_duty_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltemplate',
            name='clinic_branch',
            field=models.ForeignKey(blank=True, help_text='Specific branch this template is for. Null means all locations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_clinical_templates', to='clinics.clinic'),
        ),
    ]
