# Generated by Django 5.2.7 on 2026-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_templates', '0006_add_clinic_branch_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='chart_annotation_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
