# Generated by Django 5.2.7 on 2026-08-29 08:52

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    ClinicalNote = apps.get_model('clinical_templates', 'ClinicalNote')
    # Use update to safely handle large datasets. is_signed defaults to False, so status='drafted' is the fallback.
    ClinicalNote.objects.filter(is_signed=True).update(status='finalized')
    ClinicalNote.objects.filter(is_signed=False).update(status='drafted')

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_patient_case'),
        ('clinical_templates', '0009_clinicalnote_amendment_reason_and_more'),
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('patients', '0040_alter_patientcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('finalized', 'Finalized/Signed')], default='drafted', max_length=20),
        ),
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='clinicalnote',
            name='clinical_no_is_draf_534a05_idx',
        ),
        migrations.RemoveField(
            model_name='clinicalnote',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='clinicalnote',
            name='is_signed',
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['status'], name='clinical_no_status_3860ff_idx'),
        ),
    ]
