# Generated by Django 5.2.7 on 2026-08-31 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_templates', '0010_remove_clinicalnote_clinical_no_is_draf_534a05_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
