# Generated by Django 5.2.7 on 2026-08-03 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('BUG', 'Bug Report'), ('FEATURE_REQUEST', 'Feature Request'), ('GENERAL_FEEDBACK', 'General Feedback'), ('SUPPORT', 'Support Request'), ('PRIVACY', 'Privacy Concern'), ('SECURITY', 'Security Concern'), ('OTHER', 'Other')], default='BUG', max_length=20)),
                ('module', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('DIARY', 'Diary'), ('PATIENTS', 'Patients'), ('APPOINTMENTS', 'Appointments'), ('CASES', 'Cases'), ('CLINICAL_DOCUMENTATION', 'Clinical Documentation'), ('CLINICAL_NOTES', 'Clinical Notes'), ('SESSION_TRACKING', 'Session Tracking'), ('INVOICES', 'Invoices'), ('BILLING', 'Billing'), ('ONLINE_BOOKING', 'Online Booking'), ('NOTIFICATIONS', 'Notifications'), ('SMS', 'SMS'), ('SETUP', 'Setup'), ('SERVICES', 'Services'), ('SESSION_PACKAGES', 'Session Packages'), ('AUTHENTICATION', 'Authentication'), ('REPORTS', 'Reports'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('INVESTIGATING', 'Investigating'), ('IN_PROGRESS', 'In Progress'), ('WAITING_FOR_USER', 'Waiting for User'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to='clinics.clinic')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='support.userfeedback')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='support/attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.userfeedback')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_feedback_attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='If True, only developers/admins can see this. Normal users cannot.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.userfeedback')),
            ],
            options={
                'db_table': 'user_feedback_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('INVESTIGATING', 'Investigating'), ('IN_PROGRESS', 'In Progress'), ('WAITING_FOR_USER', 'Waiting for User'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('INVESTIGATING', 'Investigating'), ('IN_PROGRESS', 'In Progress'), ('WAITING_FOR_USER', 'Waiting for User'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional reason for the change')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_status_changes', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='support.userfeedback')),
            ],
            options={
                'db_table': 'user_feedback_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='user_feedba_status_6f2f0c_idx'),
        ),
    ]
