# Generated by Django 5.2.7 on 2026-09-05 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='resolution_message',
            field=models.TextField(blank=True, help_text='Message sent to the user when feedback is resolved.'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
