# Generated by Django 5.2.7 on 2026-09-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_userfeedback_resolution_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='resolution_message',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='resolution_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='resolution_root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='resolution_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
